import{i as y,a as E,S as C,N as x,K as _}from"./assets/vendor-vv4MlyBQ.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const s of document.querySelectorAll('link[rel="modulepreload"]'))o(s);new MutationObserver(s=>{for(const r of s)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function i(s){const r={};return s.integrity&&(r.integrity=s.integrity),s.referrerPolicy&&(r.referrerPolicy=s.referrerPolicy),s.crossOrigin==="use-credentials"?r.credentials="include":s.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function o(s){if(s.ep)return;s.ep=!0;const r=i(s);fetch(s.href,r)}})();function P({localStorageTheme:t,systemSettingDark:e}){return t!==null?t:e.matches?"dark":"light"}function w({buttonEl:t,isDark:e}){const i=e?"Switch to light theme":"Switch to dark theme";t.setAttribute("aria-label",i),t.setAttribute("title",i)}function v({theme:t}){document.querySelector("html").setAttribute("data-theme",t)}const p=document.querySelector("[data-theme-switch]"),q=localStorage.getItem("theme"),J=window.matchMedia("(prefers-color-scheme: dark)");let m=P({localStorageTheme:q,systemSettingDark:J});w({buttonEl:p,isDark:m==="dark"});v({theme:m});p.addEventListener("click",t=>{const e=m==="dark"?"light":"dark";localStorage.setItem("theme",e),w({buttonEl:p,isDark:e==="dark"}),v({theme:e}),m=e});const u=document.querySelector(".open-menu-btn"),k=document.querySelector(".menu"),T=document.querySelectorAll(".menu-link");u.addEventListener("click",()=>{k.classList.toggle("is-open"),u.classList.toggle("active")});T.forEach(t=>{t.addEventListener("click",()=>{k.classList.remove("is-open"),u.classList.remove("active")})});const I="/js_109_andrii-kyrch/assets/icons-BEahDM1L.svg",M="/js_109_andrii-kyrch/assets/wallet-webservice-Ce0EG76j.webp",B="/js_109_andrii-kyrch/assets/green-harvest-online-store-DYDdMwuz.webp",H="/js_109_andrii-kyrch/assets/english-excellence-webservice-y3-teQ4M.webp",N="/js_109_andrii-kyrch/assets/power-pulse-webservice-C4HewiA0.webp",R="/js_109_andrii-kyrch/assets/mimino-website-DDUl-gZp.webp",D="/js_109_andrii-kyrch/assets/vyshyvanka-vibes-landing-page-V5o9oPqt.webp",G="/js_109_andrii-kyrch/assets/chego-jewelry-website-BQ-wBBdr.webp",O="/js_109_andrii-kyrch/assets/energy-flow-webservice-iuvFqBQz.webp",A="/js_109_andrii-kyrch/assets/fruitbox-online-store-DWUupH6o.webp",$="/js_109_andrii-kyrch/assets/starlight-studio-landing-page-HCk1tu1y.webp",h=document.getElementById("loadMoreBtn"),z=document.querySelector(".my-projects-list");let c=0;const V=3;function f(){for(let t=0;t<V;t++)if(c<d.length){const e=d[c],i=document.createElement("li");i.classList.add("my-projects-item"),i.innerHTML=`
        <img class="project-img" src="${e.imgSrc}" alt="${e.altText}" />
        <p class="hard-skills">${e.skills}</p>
        <div class="project-item-box">
          <h3 class="project-name">${e.name}</h3>
        <a href="https://github.com/andrii-kyrch/project-CodeHeros-11/blob/main/src/js/my-projects.js" target="_blank" class="button-link">
            Visit
            <svg class="link-icon" width="24" height="24">
              <use href="${I}#arrow"></use>
            </svg>
          </a>
        </div>
      `,z.appendChild(i),c++}c>=d.length&&(h.style.display="none",y.info({title:"Info",message:"There are no more projects to display.",position:"topRight"}))}const d=[{imgSrc:M,altText:"Wallet Webservice",skills:"React, JavaScript, Node JS, Git",name:"Wallet Webservice",githubLink:"https://github.com/andrii-kyrch/project-CodeHeros-11"},{imgSrc:B,altText:"Green harvest online store",skills:"React, JavaScript, Node JS, Git",name:"Green harvest online store",githubLink:"https://github.com/andrii-kyrch/project-CodeHeros-11"},{imgSrc:H,altText:"English excellence webservice",skills:"React, JavaScript, Node JS, Git",name:"English excellence webservice",githubLink:"https://github.com/andrii-kyrch/project-CodeHeros-11"},{imgSrc:N,altText:"Power pulse webservice",skills:"React, JavaScript, Node JS, Git",name:"Power pulse webservice",githubLink:"https://github.com/andrii-kyrch/project-CodeHeros-11"},{imgSrc:R,altText:"Mimino website",skills:"React, JavaScript, Node JS, Git",name:"Mimino website",githubLink:"https://github.com/andrii-kyrch/project-CodeHeros-11"},{imgSrc:D,altText:"Vyshyvanka vibes Landing Page",skills:"React, JavaScript, Node JS, Git",name:"Vyshyvanka vibes Landing Page",githubLink:"https://github.com/andrii-kyrch/project-CodeHeros-11"},{imgSrc:G,altText:"Chego jewelry website",skills:"React, JavaScript, Node JS, Git",name:"Chego jewelry website",githubLink:"https://github.com/andrii-kyrch/project-CodeHeros-11"},{imgSrc:O,altText:"Energy flow webservice",skills:"React, JavaScript, Node JS, Git",name:"Energy flow webservice",githubLink:"https://github.com/andrii-kyrch/project-CodeHeros-11"},{imgSrc:A,altText:"Fruitbox online store",skills:"React, JavaScript, Node JS, Git",name:"Fruitbox online store",githubLink:"https://github.com/andrii-kyrch/project-CodeHeros-11"},{imgSrc:$,altText:"Starlight studio landing page",skills:"React, JavaScript, Node JS, Git",name:"Starlight studio landing page",githubLink:"https://github.com/andrii-kyrch/project-CodeHeros-11"}];h.addEventListener("click",f);document.addEventListener("DOMContentLoaded",()=>{f(),c<d.length&&(h.style.display="block")});document.addEventListener("DOMContentLoaded",function(){document.querySelectorAll(".accordion-item").forEach(e=>{e.querySelector(".accordion-header").addEventListener("click",()=>{const o=document.querySelector(".accordion-item.active");o&&o!==e&&o.classList.remove("active"),e.classList.toggle("active")})})});async function W(){const i="https://portfolio-js.b.goit.study/api"+"/reviews";return(await E.get(i)).data}function F(t,e){const i=t.map(({review:o,author:s,avatar_url:r})=>`<li class="swiper-slide reviews-item">
        <p class="reviews-text">${o}</p>
          <p class="reviews-author">
          <img src="${r}" alt="" />${s}</p>
      </li>`).join("");e.innerHTML=i}const U=document.querySelector(".swiper-wrapper"),K=document.querySelector(".reviews-prev-btn"),Q=document.querySelector(".reviews-next-btn"),Z={modules:[x,_],slidesPerView:1,slidesPerGroup:1,spaceBetween:20,slideActiveClass:"swiper-slide-active",loop:!1,keyboard:{enabled:!0},speed:500,navigation:{nextEl:".reviews-next-btn",prevEl:".reviews-prev-btn"},breakpoints:{1280:{slidesPerView:2,slidesPerGroup:2,spaceBetween:32}}};async function Y(){try{let i=function(){K.disabled=e.isBeginning,Q.disabled=e.isEnd};const t=await W();F(t,U);const e=new C(".swiper",Z);window.addEventListener("resize",()=>e.update()),i()}catch{y.error({message:"Not found",maxWidth:350,closeOnEscape:!0,closeOnClick:!0,position:"topRight"})}}Y();document.addEventListener("DOMContentLoaded",()=>{const t=document.querySelector(".feedback-form"),e=document.querySelector(".backdrop"),i=document.querySelector(".modal-close-btn"),o=document.querySelector(".input-email"),s=document.querySelector(".error-message");t.addEventListener("submit",async a=>{a.preventDefault();const g=new FormData(t),b=g.get("email"),S=g.get("message");if(/^\w+(\.\w+)?@[a-zA-Z_]+?\.[a-zA-Z]{2,3}$/.test(b))o.classList.remove("error"),s.style.display="none";else{o.classList.add("error"),s.style.display="block";return}const L={email:b,comment:S};try{const l=await fetch("https://portfolio-js.b.goit.study/api/requests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(L)});if(!l.ok){const j=await l.json();throw new Error(j.message||"Не вдалося надіслати заявку. Перевірте введені дані.")}t.reset(),r()}catch(l){alert(l.message)}});function r(){e.classList.add("is-open")}function n(){e.classList.remove("is-open")}i.addEventListener("click",n),document.addEventListener("click",a=>{a.target===e&&n()}),document.addEventListener("keydown",a=>{a.key==="Escape"&&e.classList.contains("is-open")&&n()})});
//# sourceMappingURL=index.js.map
